/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EmailVerificationStatus = {
    Verified: 'VERIFIED',
    NotVerified: 'NOT_VERIFIED'
} as const;
export type EmailVerificationStatus = typeof EmailVerificationStatus[keyof typeof EmailVerificationStatus];


export function instanceOfEmailVerificationStatus(value: any): boolean {
    return Object.values(EmailVerificationStatus).includes(value);
}

export function EmailVerificationStatusFromJSON(json: any): EmailVerificationStatus {
    return EmailVerificationStatusFromJSONTyped(json, false);
}

export function EmailVerificationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationStatus {
    return json as EmailVerificationStatus;
}

export function EmailVerificationStatusToJSON(value?: EmailVerificationStatus | null): any {
    return value as any;
}

