/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginByEmailRequestBody
 */
export interface LoginByEmailRequestBody {
    /**
     * 
     * @type {string}
     * @memberof LoginByEmailRequestBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginByEmailRequestBody
     */
    password: string;
}

/**
 * Check if a given object implements the LoginByEmailRequestBody interface.
 */
export function instanceOfLoginByEmailRequestBody(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function LoginByEmailRequestBodyFromJSON(json: any): LoginByEmailRequestBody {
    return LoginByEmailRequestBodyFromJSONTyped(json, false);
}

export function LoginByEmailRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginByEmailRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginByEmailRequestBodyToJSON(value?: LoginByEmailRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

