/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhotoPath
 */
export interface PhotoPath {
    /**
     * 
     * @type {string}
     * @memberof PhotoPath
     */
    url?: string;
}

/**
 * Check if a given object implements the PhotoPath interface.
 */
export function instanceOfPhotoPath(value: object): boolean {
    return true;
}

export function PhotoPathFromJSON(json: any): PhotoPath {
    return PhotoPathFromJSONTyped(json, false);
}

export function PhotoPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotoPath {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PhotoPathToJSON(value?: PhotoPath | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

