/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokensPair } from './TokensPair';
import {
    TokensPairFromJSON,
    TokensPairFromJSONTyped,
    TokensPairToJSON,
} from './TokensPair';

/**
 * 
 * @export
 * @interface SignUpByEmailResponseBody
 */
export interface SignUpByEmailResponseBody {
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailResponseBody
     */
    userId: string;
    /**
     * 
     * @type {TokensPair}
     * @memberof SignUpByEmailResponseBody
     */
    tokens: TokensPair;
}

/**
 * Check if a given object implements the SignUpByEmailResponseBody interface.
 */
export function instanceOfSignUpByEmailResponseBody(value: object): boolean {
    if (!('userId' in value)) return false;
    if (!('tokens' in value)) return false;
    return true;
}

export function SignUpByEmailResponseBodyFromJSON(json: any): SignUpByEmailResponseBody {
    return SignUpByEmailResponseBodyFromJSONTyped(json, false);
}

export function SignUpByEmailResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpByEmailResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'tokens': TokensPairFromJSON(json['tokens']),
    };
}

export function SignUpByEmailResponseBodyToJSON(value?: SignUpByEmailResponseBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'tokens': TokensPairToJSON(value['tokens']),
    };
}

