/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FullName } from './FullName';
import {
    FullNameFromJSON,
    FullNameFromJSONTyped,
    FullNameToJSON,
} from './FullName';

/**
 * 
 * @export
 * @interface SignUpByEmailRequestBody
 */
export interface SignUpByEmailRequestBody {
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailRequestBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailRequestBody
     */
    password: string;
    /**
     * 
     * @type {FullName}
     * @memberof SignUpByEmailRequestBody
     */
    fullName: FullName;
}

/**
 * Check if a given object implements the SignUpByEmailRequestBody interface.
 */
export function instanceOfSignUpByEmailRequestBody(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    if (!('fullName' in value)) return false;
    return true;
}

export function SignUpByEmailRequestBodyFromJSON(json: any): SignUpByEmailRequestBody {
    return SignUpByEmailRequestBodyFromJSONTyped(json, false);
}

export function SignUpByEmailRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpByEmailRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'fullName': FullNameFromJSON(json['fullName']),
    };
}

export function SignUpByEmailRequestBodyToJSON(value?: SignUpByEmailRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
        'fullName': FullNameToJSON(value['fullName']),
    };
}

