/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokensPair
 */
export interface TokensPair {
    /**
     * 
     * @type {string}
     * @memberof TokensPair
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof TokensPair
     */
    refresh: string;
}

/**
 * Check if a given object implements the TokensPair interface.
 */
export function instanceOfTokensPair(value: object): boolean {
    if (!('access' in value)) return false;
    if (!('refresh' in value)) return false;
    return true;
}

export function TokensPairFromJSON(json: any): TokensPair {
    return TokensPairFromJSONTyped(json, false);
}

export function TokensPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokensPair {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'],
        'refresh': json['refresh'],
    };
}

export function TokensPairToJSON(value?: TokensPair | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access': value['access'],
        'refresh': value['refresh'],
    };
}

