/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadedFileData
 */
export interface UploadedFileData {
    /**
     * 
     * @type {string}
     * @memberof UploadedFileData
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof UploadedFileData
     */
    bucketName: string;
    /**
     * 
     * @type {string}
     * @memberof UploadedFileData
     */
    objectName: string;
}

/**
 * Check if a given object implements the UploadedFileData interface.
 */
export function instanceOfUploadedFileData(value: object): boolean {
    if (!('url' in value)) return false;
    if (!('bucketName' in value)) return false;
    if (!('objectName' in value)) return false;
    return true;
}

export function UploadedFileDataFromJSON(json: any): UploadedFileData {
    return UploadedFileDataFromJSONTyped(json, false);
}

export function UploadedFileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadedFileData {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'bucketName': json['bucketName'],
        'objectName': json['objectName'],
    };
}

export function UploadedFileDataToJSON(value?: UploadedFileData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'bucketName': value['bucketName'],
        'objectName': value['objectName'],
    };
}

