/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorDetails
 */
export interface ValidationErrorDetails {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetails
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetails
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetails
     */
    code: string;
}

/**
 * Check if a given object implements the ValidationErrorDetails interface.
 */
export function instanceOfValidationErrorDetails(value: object): boolean {
    if (!('path' in value)) return false;
    if (!('message' in value)) return false;
    if (!('code' in value)) return false;
    return true;
}

export function ValidationErrorDetailsFromJSON(json: any): ValidationErrorDetails {
    return ValidationErrorDetailsFromJSONTyped(json, false);
}

export function ValidationErrorDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'message': json['message'],
        'code': json['code'],
    };
}

export function ValidationErrorDetailsToJSON(value?: ValidationErrorDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'path': value['path'],
        'message': value['message'],
        'code': value['code'],
    };
}

