/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ModelError } from './ModelError';
import {
    instanceOfModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import type { ValidationError } from './ValidationError';
import {
    instanceOfValidationError,
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
} from './ValidationError';

/**
 * @type VerifyEmail400Response
 * 
 * @export
 */
export type VerifyEmail400Response = ModelError | ValidationError;

export function VerifyEmail400ResponseFromJSON(json: any): VerifyEmail400Response {
    return VerifyEmail400ResponseFromJSONTyped(json, false);
}

export function VerifyEmail400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmail400Response {
    if (json == null) {
        return json;
    }
    return ModelErrorFromJSONTyped(json, true) || ValidationErrorFromJSONTyped(json, true);
}

export function VerifyEmail400ResponseToJSON(value?: VerifyEmail400Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfModelError(value)) {
        return ModelErrorToJSON(value as ModelError);
    }
    if (instanceOfValidationError(value)) {
        return ValidationErrorToJSON(value as ValidationError);
    }

    return {};
}

