/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyEmail200Response
 */
export interface VerifyEmail200Response {
    /**
     * 
     * @type {string}
     * @memberof VerifyEmail200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the VerifyEmail200Response interface.
 */
export function instanceOfVerifyEmail200Response(value: object): boolean {
    return true;
}

export function VerifyEmail200ResponseFromJSON(json: any): VerifyEmail200Response {
    return VerifyEmail200ResponseFromJSONTyped(json, false);
}

export function VerifyEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmail200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function VerifyEmail200ResponseToJSON(value?: VerifyEmail200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

