openapi: 3.0.3
info:
  title: Models
  description: Models
  version: 1.0.0
paths:
  /:
components:
  schemas:
    AddListingRequestBody:
      type: object
      required:
        - operationId
        - title
      properties:
        operationId:
          $ref: "../../../common/models/OperationId.yaml"
        title:
          type: string
          maxLength: 1000

    AddListingResponse:
      type: object
      required:
        - listingId
      properties:
        listingId:
          $ref: "../../common/models/ListingId.yaml"

    UpdateListingDetailsRequestBody:
      type: object
      required:
        - operationId
        - listingId
        - fields
      properties:
        operationId:
          $ref: "../../../common/models/OperationId.yaml"
        fields:
            $ref: "#/components/schemas/UpdateListingDetailsFields"

    UpdateListingDetailsFields:
      type: object
      properties:
        title:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 2000
          nullable: true
        guestCapacity:
          nullable: true
          allOf:
            - $ref: "../../common/models/GuestsCapacity.yaml"
        propertyType:
          nullable: true
          allOf:
            - $ref: "../../common/models/PropertyType.yaml"
        roomType:
          nullable: true
          allOf:
            - $ref: "../../common/models/RoomType.yaml"
        address:
          nullable: true
          allOf:
            - $ref: "../../common/models/Address.yaml"
