openapi: 3.0.3
info:
  title: Models
  description: Models
  version: 1.0.0
paths:
  /:
components:
  schemas:
    AddListingRequestBody:
      type: object
      required:
        - operationId
        - title
      properties:
        operationId:
          $ref: "../../../common/models/OperationIdDTO.yaml"
        title:
          type: string
          maxLength: 1000

    AddListingResponse:
      type: object
      required:
        - listingId
      properties:
        listingId:
          $ref: "../../common/models/ListingIdDTO.yaml"

    UpdateListingDetailsRequestBody:
      type: object
      required:
        - operationId
        - listingId
      properties:
        operationId:
          $ref: "../../../common/models/OperationIdDTO.yaml"
        fields:
            $ref: "#/components/schemas/UpdateListingDetailsFieldsDTO"

    UpdateListingDetailsFieldsDTO:
      type: object
      properties:
        title:
          type: string
          maxLength: 1000
        description:
          type: string
        maxLength: 10000
        guestCapacity:
          $ref: "../../common/models/GuestsCapacityDTO.yaml"
        propertyType:
          $ref: "../../common/models/PropertyTypeDTO.yaml"
        roomType:
          $ref: "../../common/models/RoomTypeDTO.yaml"
        address:
          $ref: "../../common/models/AddressDTO.yaml"
