openapi: 3.0.3
info:
  title: Listings Commands API
  description: Listings Commands API
  version: 1.0.0
paths:
  /listings:
    post:
      tags:
        - commandsModifications
      summary: Add a new listing
      operationId: addListing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models.yaml#/components/schemas/AddListingRequestBody"
      responses:
        "200":
          description: Listing added successfully
          content:
            application/json:
              schema:
                "$ref": "models.yaml#/components/schemas/AddListingResponse"
        "401":
          description: Not valid Token
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../../common/errors.yaml#/ValidationError"
                  - $ref: "../../../common/errors.yaml#/Error"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "../../../common/errors.yaml#/Error"

  /listings/{listingId}:
    patch:
      tags:
        - commandsModifications
      summary: Update listing details
      operationId: updateListingDetails
      parameters:
        - name: listingId
          in: path
          required: true
          description: Listing ID
          schema:
            $ref: "../../common/models/ListingId.yaml"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models.yaml#/components/schemas/UpdateListingDetailsRequestBody"
      responses:
        "201":
          description: Listing updated successfully
        "401":
          description: Validation error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../../common/errors.yaml#/ValidationError"
                  - $ref: "../../../common/errors.yaml#/Error"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "../../../common/errors.yaml#/Error"
        "404":
          description: Listing not found
          content:
            application/json:
              schema:
                $ref: "../../../common/errors.yaml#/Error"