version: "2"

services:
  debug-email:
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"

  eureka:
    image: booking-demo/eureka:0.0.1-SNAPSHOT
    environment:
        - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}

  gateway:
    image: booking-demo/gateway:0.0.1-SNAPSHOT
    depends_on:
      - eureka
      - users-ms
      - listings-ms
    environment:
        - GATEWAY_EUREKA=http://eureka:${EUREKA_SERVER_PORT}/eureka/
        - GATEWAY_PORT=${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

  users-db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: ${USERS_DB_USERNAME}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB_NAME}

  users-ms:
    image: booking-demo/users-ms:0.0.1-SNAPSHOT
    depends_on:
      - users-db
      - objects-storage
      - broker
      - eureka
    environment:
      - USERS_MS_PORT=${USERS_MS_PORT}
      - USERS_MS_EUREKA=http://eureka:${EUREKA_SERVER_PORT}/eureka/
      - USERS_MS_DB_HOST=users-db
      - USERS_MS_DB_PORT=${USERS_DB_PORT}
      - USERS_MS_DB_NAME=${USERS_DB_NAME}
      - USERS_MS_DB_USERNAME=${USERS_DB_USERNAME}
      - USERS_MS_DB_PASSWORD=${USERS_DB_PASSWORD}
      - USERS_MS_RESET_PASSWORD_TOKEN_EXPIRATION_IN_MS=3600000
      - USERS_MS_RESET_PASSWORD_OUTGOING_EMAIL_FROM_NAME=Username
      - USERS_MS_RESET_PASSWORD_OUTGOING_EMAIL_FROM_ADDRESS=noreply@resetpassword.com
      - USERS_MS_RESET_PASSWORD_OUTGOING_EMAIL_SUBJECT=Reset your password
      - USERS_MS_RESET_PASSWORD_BASE_VERIFICATION_LINK_URL=${GATEWAY_BASE_URL}/reset-password
      - USERS_MS_PHOTO_ENDPOINT=http://localhost:9000
      - USERS_MS_PHOTO_BUCKET_NAME=users-photos
      - USERS_MS_MINIO_ACCESS_KEY=minio-root-user
      - USERS_MS_MINIO_SECRET_KEY=minio-root-password
      - USERS_MS_PHOTO_UPLOAD_URL_EXPIRES_IN_SECONDS=300
      - USERS_MS_VERIFICATION_EMAIL_TOKEN_EXPIRATION_IN_MS=3600000
      - USERS_MS_VERIFICATION_EMAIL_OUTGOING_FROM_NAME=Username
      - USERS_MS_VERIFICATION_EMAIL_OUTGOING_FROM_ADDRESS=noreply@mail.com
      - USERS_MS_VERIFICATION_EMAIL_BASE_VERIFICATION_LINK_URL=${GATEWAY_BASE_URL}/verify-email
      - USERS_MS_MAIL_SERVER_USERNAME=${MAIL_SERVER_USERNAME}
      - USERS_MS_MAIL_SERVER_PASSWORD=${MAIL_SERVER_PASSWORD}
      - USERS_MS_MAIL_SERVER_HOST=debug-email
      - USERS_MS_MAIL_SERVER_PORT=${MAIL_SERVER_PORT}
      - USERS_MS_MAIL_SERVER_PROTOCOL=${MAIL_SERVER_PROTOCOL}
      - USERS_MS_KAFKA_SERVER=broker:${BROKER_PORT}
      - USERS_MS_KAFKA_CONSUMER_GROUP_ID=users-ms-group

  listings-db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: ${LISTINGS_DB_NAME}
      POSTGRES_USER: ${LISTINGS_DB_USERNAME}
      POSTGRES_PASSWORD: ${LISTINGS_DB_PASSWORD}

  listings-ms:
    image: booking-demo/listings-ms:0.0.1-SNAPSHOT
    depends_on:
      - listings-db
      - objects-storage
      - broker
      - eureka
    environment:
      - LISTINGS_MS_PORT=${LISTINGS_MS_PORT}
      - LISTINGS_MS_EUREKA=http://eureka:${EUREKA_SERVER_PORT}/eureka/

      - LISTINGS_MS_DB_HOST=listings-db
      - LISTINGS_MS_DB_PORT=${LISTINGS_DB_PORT}
      - LISTINGS_MS_DB_NAME=${LISTINGS_DB_NAME}
      - LISTINGS_MS_DB_USERNAME=${LISTINGS_DB_USERNAME}
      - LISTINGS_MS_DB_PASSWORD=${LISTINGS_DB_PASSWORD}

      - LISTINGS_MS_RESET_PASSWORD_BASE_VERIFICATION_LINK_URL=${GATEWAY_BASE_URL}/reset-password
      - LISTINGS_MS_PHOTO_ENDPOINT=http://localhost:9000
      - LISTINGS_MS_PHOTO_BUCKET_NAME=listings-photos
      - LISTINGS_MS_MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - LISTINGS_MS_MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - LISTINGS_MS_PHOTO_UPLOAD_URL_EXPIRES_IN_SECONDS=300
      - LISTINGS_MS_VERIFICATION_EMAIL_TOKEN_EXPIRATION_IN_MS=3600000
      - LISTINGS_MS_VERIFICATION_EMAIL_OUTGOING_FROM_NAME=Username
      - LISTINGS_MS_VERIFICATION_EMAIL_OUTGOING_FROM_ADDRESS=noreply@mail.com
      - LISTINGS_MS_VERIFICATION_EMAIL_BASE_VERIFICATION_LINK_URL=${GATEWAY_BASE_URL}/verify-email
      - LISTINGS_MS_MAIL_SERVER_USERNAME=${MAIL_SERVER_USERNAME}
      - LISTINGS_MS_MAIL_SERVER_PASSWORD=${MAIL_SERVER_PASSWORD}
      - LISTINGS_MS_MAIL_SERVER_HOST=debug-email
      - LISTINGS_MS_MAIL_SERVER_PORT=${MAIL_SERVER_PORT}
      - LISTINGS_MS_MAIL_SERVER_PROTOCOL=${MAIL_SERVER_PROTOCOL}
      - LISTINGS_MS_KAFKA_SERVER=broker:${BROKER_PORT}
      - LISTINGS_MS_KAFKA_CONSUMER_GROUP_ID=listings-ms-group

  objects-storage:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001" # MinIO Console
    command:
      - server
      - /data
      - --console-address
      - ":9001"

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

volumes:
  kafka_data:
    driver: local
  minio-data:
    driver: local