openapi: 3.0.0
info:
  description: Describes the API of Listings service
  title: Listings API
  version: 1.0.0
servers:
- url: /
security:
- BearerAuth: []
paths:
  /api/private/users/currrent/listings/{listingId}:
    get:
      operationId: getListingPrivateDetails
      parameters:
      - description: Listing ID
        in: path
        name: listingId
        required: true
        schema:
          $ref: '#/components/schemas/ListingIdDTO'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetListingPrivateDetailsResponse'
          description: Private details of listing
        "401":
          description: Not valid Token
        "404":
          description: Not found
      summary: Get private details for listing
      tags:
      - queriesPrivate
      x-accepts: application/json
  /api/private/listings:
    post:
      operationId: addListing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddListingRequestBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddListingResponse'
          description: Listing added successfully
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addListing_401_response'
          description: Not valid Token
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
          description: Not found
      summary: Add a new listing
      tags:
      - commandsModifications
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    ListingIdDTO:
      format: uuid
      type: string
    GetListingPrivateDetailsResponse:
      example:
        listing:
          description: description
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          title: title
      properties:
        listing:
          $ref: '#/components/schemas/ListingPrivateDetailsDTO'
      required:
      - listing
      type: object
    ListingPrivateDetailsDTO:
      example:
        description: description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        title: title
      properties:
        id:
          format: uuid
          type: string
        title:
          type: string
        description:
          type: string
      required:
      - id
      - title
      type: object
    AddListingRequestBody:
      example:
        operationId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        title: title
      properties:
        operationId:
          format: uuid
          type: string
        title:
          maxLength: 1000
          type: string
      required:
      - operationId
      - title
      type: object
    AddListingResponse:
      example:
        listingId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        listingId:
          format: uuid
          type: string
      required:
      - listingId
      type: object
    ValidationErrorDTO:
      properties:
        type:
          default: validationError
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ValidationErrorDetailsDTO'
          type: array
      required:
      - errors
      - type
      type: object
    ValidationErrorDetailsDTO:
      properties:
        path:
          type: string
        message:
          type: string
        code:
          type: string
      required:
      - code
      - message
      - path
      type: object
    ErrorDTO:
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
      type: object
    OperationIdDTO:
      format: uuid
      type: string
    addListing_401_response:
      oneOf:
      - $ref: '#/components/schemas/ValidationErrorDTO'
      - $ref: '#/components/schemas/ErrorDTO'
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http

