openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Listings API"
  description: Describes the API of Listings service

paths:
  # Modification API

  /api/private/users/currrent/listings/{listingId}:
    $ref: "queries/private/paths.yaml#/paths/~1listings~1{listingId}"

  /api/private/users/currrent/listings:
    $ref: "queries/private/paths.yaml#/paths/~1listings"

  /api/private/listings:
    $ref: "commands/modification/paths.yaml#/paths/~1listings"

  /api/private/listings/{listingId}:
    $ref: "commands/modification/paths.yaml#/paths/~1listings~1{listingId}"

  #  Photos API

  /api/private/listings/{listingId}/photos/get-upload-url:
    $ref: "commands/attach-photo/paths.yaml#/paths/~1listings~1{listingId}~1photos~1get-upload-url"

  /api/private/listings/{listingId}/photos/add:
    $ref: "commands/attach-photo/paths.yaml#/paths/~1listings~1{listingId}~1photos~1add"

  /api/private/listings/{listingId}/photos/{photoId}:
    $ref: "commands/attach-photo/paths.yaml#/paths/~1listings~1{listingId}~1photos~1{photoId}"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: [ ]
