openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Listings API"
  description: Describes the API of Listings service

paths:
  /api/private/users/currrent/listings/{listingId}:
    $ref: "queries/private/paths.yaml#/paths/~1listings~1{listingId}"

  /api/private/listings:
    $ref: "commands/modification/paths.yaml#/paths/~1listings"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: [ ]
