/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPublicAuthTokenVerifyPostRequest
 */
export interface ApiPublicAuthTokenVerifyPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiPublicAuthTokenVerifyPostRequest
     */
    token: string;
}

/**
 * Check if a given object implements the ApiPublicAuthTokenVerifyPostRequest interface.
 */
export function instanceOfApiPublicAuthTokenVerifyPostRequest(value: object): boolean {
    if (!('token' in value)) return false;
    return true;
}

export function ApiPublicAuthTokenVerifyPostRequestFromJSON(json: any): ApiPublicAuthTokenVerifyPostRequest {
    return ApiPublicAuthTokenVerifyPostRequestFromJSONTyped(json, false);
}

export function ApiPublicAuthTokenVerifyPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublicAuthTokenVerifyPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function ApiPublicAuthTokenVerifyPostRequestToJSON(value?: ApiPublicAuthTokenVerifyPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

