/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ValidationError } from './ValidationError';
import {
    instanceOfValidationError,
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
} from './ValidationError';

/**
 * @type ApiPublicAuthSignUpPost400Response
 * 
 * @export
 */
export type ApiPublicAuthSignUpPost400Response = ValidationError;

export function ApiPublicAuthSignUpPost400ResponseFromJSON(json: any): ApiPublicAuthSignUpPost400Response {
    return ApiPublicAuthSignUpPost400ResponseFromJSONTyped(json, false);
}

export function ApiPublicAuthSignUpPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublicAuthSignUpPost400Response {
    if (json == null) {
        return json;
    }
    return ValidationErrorFromJSONTyped(json, true);
}

export function ApiPublicAuthSignUpPost400ResponseToJSON(value?: ApiPublicAuthSignUpPost400Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfValidationError(value)) {
        return ValidationErrorToJSON(value as ValidationError);
    }

    return {};
}

