/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiPublicAuthTokenPostRequest
 */
export interface ApiPublicAuthTokenPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiPublicAuthTokenPostRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPublicAuthTokenPostRequest
     */
    password: string;
}

/**
 * Check if a given object implements the ApiPublicAuthTokenPostRequest interface.
 */
export function instanceOfApiPublicAuthTokenPostRequest(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function ApiPublicAuthTokenPostRequestFromJSON(json: any): ApiPublicAuthTokenPostRequest {
    return ApiPublicAuthTokenPostRequestFromJSONTyped(json, false);
}

export function ApiPublicAuthTokenPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPublicAuthTokenPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function ApiPublicAuthTokenPostRequestToJSON(value?: ApiPublicAuthTokenPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

