/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateByEmailRequest
 */
export interface AuthenticateByEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateByEmailRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateByEmailRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticateByEmailRequest interface.
 */
export function instanceOfAuthenticateByEmailRequest(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function AuthenticateByEmailRequestFromJSON(json: any): AuthenticateByEmailRequest {
    return AuthenticateByEmailRequestFromJSONTyped(json, false);
}

export function AuthenticateByEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateByEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthenticateByEmailRequestToJSON(value?: AuthenticateByEmailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

