/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateByEmailResponse
 */
export interface AuthenticateByEmailResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateByEmailResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateByEmailResponse
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticateByEmailResponse interface.
 */
export function instanceOfAuthenticateByEmailResponse(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function AuthenticateByEmailResponseFromJSON(json: any): AuthenticateByEmailResponse {
    return AuthenticateByEmailResponseFromJSONTyped(json, false);
}

export function AuthenticateByEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateByEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthenticateByEmailResponseToJSON(value?: AuthenticateByEmailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

