/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EmailVerificationStatusDTO = {
    Verified: 'VERIFIED',
    NotVerified: 'NOT_VERIFIED'
} as const;
export type EmailVerificationStatusDTO = typeof EmailVerificationStatusDTO[keyof typeof EmailVerificationStatusDTO];


export function instanceOfEmailVerificationStatusDTO(value: any): boolean {
    return Object.values(EmailVerificationStatusDTO).includes(value);
}

export function EmailVerificationStatusDTOFromJSON(json: any): EmailVerificationStatusDTO {
    return EmailVerificationStatusDTOFromJSONTyped(json, false);
}

export function EmailVerificationStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationStatusDTO {
    return json as EmailVerificationStatusDTO;
}

export function EmailVerificationStatusDTOToJSON(value?: EmailVerificationStatusDTO | null): any {
    return value as any;
}

