/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FullName
 */
export interface FullName {
    /**
     * 
     * @type {string}
     * @memberof FullName
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof FullName
     */
    lastName: string;
}

/**
 * Check if a given object implements the FullName interface.
 */
export function instanceOfFullName(value: object): boolean {
    if (!('firstName' in value)) return false;
    if (!('lastName' in value)) return false;
    return true;
}

export function FullNameFromJSON(json: any): FullName {
    return FullNameFromJSONTyped(json, false);
}

export function FullNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullName {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function FullNameToJSON(value?: FullName | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

