/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FullNameDTO
 */
export interface FullNameDTO {
    /**
     * 
     * @type {string}
     * @memberof FullNameDTO
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof FullNameDTO
     */
    lastName: string;
}

/**
 * Check if a given object implements the FullNameDTO interface.
 */
export function instanceOfFullNameDTO(value: object): boolean {
    if (!('firstName' in value)) return false;
    if (!('lastName' in value)) return false;
    return true;
}

export function FullNameDTOFromJSON(json: any): FullNameDTO {
    return FullNameDTOFromJSONTyped(json, false);
}

export function FullNameDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullNameDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function FullNameDTOToJSON(value?: FullNameDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

