/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadedFileDataDTO } from './UploadedFileDataDTO';
import {
    UploadedFileDataDTOFromJSON,
    UploadedFileDataDTOFromJSONTyped,
    UploadedFileDataDTOToJSON,
} from './UploadedFileDataDTO';

/**
 * 
 * @export
 * @interface GenerateUploadUserPhotoUrlResponse
 */
export interface GenerateUploadUserPhotoUrlResponse {
    /**
     * 
     * @type {UploadedFileDataDTO}
     * @memberof GenerateUploadUserPhotoUrlResponse
     */
    objectPath: UploadedFileDataDTO;
    /**
     * 
     * @type {object}
     * @memberof GenerateUploadUserPhotoUrlResponse
     */
    formData: object;
}

/**
 * Check if a given object implements the GenerateUploadUserPhotoUrlResponse interface.
 */
export function instanceOfGenerateUploadUserPhotoUrlResponse(value: object): boolean {
    if (!('objectPath' in value)) return false;
    if (!('formData' in value)) return false;
    return true;
}

export function GenerateUploadUserPhotoUrlResponseFromJSON(json: any): GenerateUploadUserPhotoUrlResponse {
    return GenerateUploadUserPhotoUrlResponseFromJSONTyped(json, false);
}

export function GenerateUploadUserPhotoUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateUploadUserPhotoUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'objectPath': UploadedFileDataDTOFromJSON(json['objectPath']),
        'formData': json['formData'],
    };
}

export function GenerateUploadUserPhotoUrlResponseToJSON(value?: GenerateUploadUserPhotoUrlResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'objectPath': UploadedFileDataDTOToJSON(value['objectPath']),
        'formData': value['formData'],
    };
}

