/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTokenResponseTokens
 */
export interface GetTokenResponseTokens {
    /**
     * 
     * @type {string}
     * @memberof GetTokenResponseTokens
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof GetTokenResponseTokens
     */
    refresh: string;
}

/**
 * Check if a given object implements the GetTokenResponseTokens interface.
 */
export function instanceOfGetTokenResponseTokens(value: object): boolean {
    if (!('access' in value)) return false;
    if (!('refresh' in value)) return false;
    return true;
}

export function GetTokenResponseTokensFromJSON(json: any): GetTokenResponseTokens {
    return GetTokenResponseTokensFromJSONTyped(json, false);
}

export function GetTokenResponseTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTokenResponseTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'],
        'refresh': json['refresh'],
    };
}

export function GetTokenResponseTokensToJSON(value?: GetTokenResponseTokens | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access': value['access'],
        'refresh': value['refresh'],
    };
}

