/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailVerificationStatusDTO } from './EmailVerificationStatusDTO';
import {
    EmailVerificationStatusDTOFromJSON,
    EmailVerificationStatusDTOFromJSONTyped,
    EmailVerificationStatusDTOToJSON,
} from './EmailVerificationStatusDTO';
import type { FullNameDTO } from './FullNameDTO';
import {
    FullNameDTOFromJSON,
    FullNameDTOFromJSONTyped,
    FullNameDTOToJSON,
} from './FullNameDTO';
import type { PhotoPathDTO } from './PhotoPathDTO';
import {
    PhotoPathDTOFromJSON,
    PhotoPathDTOFromJSONTyped,
    PhotoPathDTOToJSON,
} from './PhotoPathDTO';

/**
 * 
 * @export
 * @interface PersonalUserInfoDTO
 */
export interface PersonalUserInfoDTO {
    /**
     * 
     * @type {string}
     * @memberof PersonalUserInfoDTO
     */
    id: string;
    /**
     * 
     * @type {FullNameDTO}
     * @memberof PersonalUserInfoDTO
     */
    fullName: FullNameDTO;
    /**
     * 
     * @type {string}
     * @memberof PersonalUserInfoDTO
     */
    email: string;
    /**
     * 
     * @type {PhotoPathDTO}
     * @memberof PersonalUserInfoDTO
     */
    photo?: PhotoPathDTO;
    /**
     * 
     * @type {EmailVerificationStatusDTO}
     * @memberof PersonalUserInfoDTO
     */
    emailVerificationStatus: EmailVerificationStatusDTO;
}

/**
 * Check if a given object implements the PersonalUserInfoDTO interface.
 */
export function instanceOfPersonalUserInfoDTO(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('fullName' in value)) return false;
    if (!('email' in value)) return false;
    if (!('emailVerificationStatus' in value)) return false;
    return true;
}

export function PersonalUserInfoDTOFromJSON(json: any): PersonalUserInfoDTO {
    return PersonalUserInfoDTOFromJSONTyped(json, false);
}

export function PersonalUserInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalUserInfoDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fullName': FullNameDTOFromJSON(json['fullName']),
        'email': json['email'],
        'photo': json['photo'] == null ? undefined : PhotoPathDTOFromJSON(json['photo']),
        'emailVerificationStatus': EmailVerificationStatusDTOFromJSON(json['emailVerificationStatus']),
    };
}

export function PersonalUserInfoDTOToJSON(value?: PersonalUserInfoDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'fullName': FullNameDTOToJSON(value['fullName']),
        'email': value['email'],
        'photo': PhotoPathDTOToJSON(value['photo']),
        'emailVerificationStatus': EmailVerificationStatusDTOToJSON(value['emailVerificationStatus']),
    };
}

