/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhotoPathDTO
 */
export interface PhotoPathDTO {
    /**
     * 
     * @type {string}
     * @memberof PhotoPathDTO
     */
    url?: string;
}

/**
 * Check if a given object implements the PhotoPathDTO interface.
 */
export function instanceOfPhotoPathDTO(value: object): boolean {
    return true;
}

export function PhotoPathDTOFromJSON(json: any): PhotoPathDTO {
    return PhotoPathDTOFromJSONTyped(json, false);
}

export function PhotoPathDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotoPathDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PhotoPathDTOToJSON(value?: PhotoPathDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

