/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordByEmailRequestBody
 */
export interface ResetPasswordByEmailRequestBody {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordByEmailRequestBody
     */
    operationId: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordByEmailRequestBody
     */
    email: string;
}

/**
 * Check if a given object implements the ResetPasswordByEmailRequestBody interface.
 */
export function instanceOfResetPasswordByEmailRequestBody(value: object): boolean {
    if (!('operationId' in value)) return false;
    if (!('email' in value)) return false;
    return true;
}

export function ResetPasswordByEmailRequestBodyFromJSON(json: any): ResetPasswordByEmailRequestBody {
    return ResetPasswordByEmailRequestBodyFromJSONTyped(json, false);
}

export function ResetPasswordByEmailRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordByEmailRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operationId'],
        'email': json['email'],
    };
}

export function ResetPasswordByEmailRequestBodyToJSON(value?: ResetPasswordByEmailRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operationId': value['operationId'],
        'email': value['email'],
    };
}

