/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordByEmail200Response
 */
export interface ResetPasswordByEmail200Response {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordByEmail200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ResetPasswordByEmail200Response interface.
 */
export function instanceOfResetPasswordByEmail200Response(value: object): boolean {
    return true;
}

export function ResetPasswordByEmail200ResponseFromJSON(json: any): ResetPasswordByEmail200Response {
    return ResetPasswordByEmail200ResponseFromJSONTyped(json, false);
}

export function ResetPasswordByEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordByEmail200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResetPasswordByEmail200ResponseToJSON(value?: ResetPasswordByEmail200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

