/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignUpByEmailResponseTokens } from './SignUpByEmailResponseTokens';
import {
    SignUpByEmailResponseTokensFromJSON,
    SignUpByEmailResponseTokensFromJSONTyped,
    SignUpByEmailResponseTokensToJSON,
} from './SignUpByEmailResponseTokens';

/**
 * 
 * @export
 * @interface SignUpByEmailResponse
 */
export interface SignUpByEmailResponse {
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailResponse
     */
    userId: string;
    /**
     * 
     * @type {SignUpByEmailResponseTokens}
     * @memberof SignUpByEmailResponse
     */
    tokens: SignUpByEmailResponseTokens;
}

/**
 * Check if a given object implements the SignUpByEmailResponse interface.
 */
export function instanceOfSignUpByEmailResponse(value: object): boolean {
    if (!('userId' in value)) return false;
    if (!('tokens' in value)) return false;
    return true;
}

export function SignUpByEmailResponseFromJSON(json: any): SignUpByEmailResponse {
    return SignUpByEmailResponseFromJSONTyped(json, false);
}

export function SignUpByEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpByEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'tokens': SignUpByEmailResponseTokensFromJSON(json['tokens']),
    };
}

export function SignUpByEmailResponseToJSON(value?: SignUpByEmailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'tokens': SignUpByEmailResponseTokensToJSON(value['tokens']),
    };
}

