/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpByEmailResponseTokens
 */
export interface SignUpByEmailResponseTokens {
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailResponseTokens
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailResponseTokens
     */
    refresh: string;
}

/**
 * Check if a given object implements the SignUpByEmailResponseTokens interface.
 */
export function instanceOfSignUpByEmailResponseTokens(value: object): boolean {
    if (!('access' in value)) return false;
    if (!('refresh' in value)) return false;
    return true;
}

export function SignUpByEmailResponseTokensFromJSON(json: any): SignUpByEmailResponseTokens {
    return SignUpByEmailResponseTokensFromJSONTyped(json, false);
}

export function SignUpByEmailResponseTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpByEmailResponseTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'],
        'refresh': json['refresh'],
    };
}

export function SignUpByEmailResponseTokensToJSON(value?: SignUpByEmailResponseTokens | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access': value['access'],
        'refresh': value['refresh'],
    };
}

