/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpResponseTokens
 */
export interface SignUpResponseTokens {
    /**
     * 
     * @type {string}
     * @memberof SignUpResponseTokens
     */
    refresh: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpResponseTokens
     */
    access: string;
}

/**
 * Check if a given object implements the SignUpResponseTokens interface.
 */
export function instanceOfSignUpResponseTokens(value: object): boolean {
    if (!('refresh' in value)) return false;
    if (!('access' in value)) return false;
    return true;
}

export function SignUpResponseTokensFromJSON(json: any): SignUpResponseTokens {
    return SignUpResponseTokensFromJSONTyped(json, false);
}

export function SignUpResponseTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpResponseTokens {
    if (json == null) {
        return json;
    }
    return {
        
        'refresh': json['refresh'],
        'access': json['access'],
    };
}

export function SignUpResponseTokensToJSON(value?: SignUpResponseTokens | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'refresh': value['refresh'],
        'access': value['access'],
    };
}

