/* tslint:disable */
/* eslint-disable */
/**
 * Demo Booking API
 * Describes the API of Daily Tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FullName } from './FullName';
import {
    FullNameFromJSON,
    FullNameFromJSONTyped,
    FullNameToJSON,
} from './FullName';

/**
 * 
 * @export
 * @interface SignUpByEmailRequest
 */
export interface SignUpByEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpByEmailRequest
     */
    password: string;
    /**
     * 
     * @type {FullName}
     * @memberof SignUpByEmailRequest
     */
    fullName: FullName;
}

/**
 * Check if a given object implements the SignUpByEmailRequest interface.
 */
export function instanceOfSignUpByEmailRequest(value: object): boolean {
    if (!('email' in value)) return false;
    if (!('password' in value)) return false;
    if (!('fullName' in value)) return false;
    return true;
}

export function SignUpByEmailRequestFromJSON(json: any): SignUpByEmailRequest {
    return SignUpByEmailRequestFromJSONTyped(json, false);
}

export function SignUpByEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpByEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'fullName': FullNameFromJSON(json['fullName']),
    };
}

export function SignUpByEmailRequestToJSON(value?: SignUpByEmailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
        'fullName': FullNameToJSON(value['fullName']),
    };
}

