/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadedFileDataDTO } from './UploadedFileDataDTO';
import {
    UploadedFileDataDTOFromJSON,
    UploadedFileDataDTOFromJSONTyped,
    UploadedFileDataDTOToJSON,
} from './UploadedFileDataDTO';

/**
 * 
 * @export
 * @interface UpdateUserPhotoRequest
 */
export interface UpdateUserPhotoRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPhotoRequest
     */
    idempotentOperationId: string;
    /**
     * 
     * @type {UploadedFileDataDTO}
     * @memberof UpdateUserPhotoRequest
     */
    uploadedFile?: UploadedFileDataDTO;
}

/**
 * Check if a given object implements the UpdateUserPhotoRequest interface.
 */
export function instanceOfUpdateUserPhotoRequest(value: object): boolean {
    if (!('idempotentOperationId' in value)) return false;
    return true;
}

export function UpdateUserPhotoRequestFromJSON(json: any): UpdateUserPhotoRequest {
    return UpdateUserPhotoRequestFromJSONTyped(json, false);
}

export function UpdateUserPhotoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPhotoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotentOperationId': json['idempotentOperationId'],
        'uploadedFile': json['uploadedFile'] == null ? undefined : UploadedFileDataDTOFromJSON(json['uploadedFile']),
    };
}

export function UpdateUserPhotoRequestToJSON(value?: UpdateUserPhotoRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idempotentOperationId': value['idempotentOperationId'],
        'uploadedFile': UploadedFileDataDTOToJSON(value['uploadedFile']),
    };
}

