/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadedFileDataDTO } from './UploadedFileDataDTO';
import {
    UploadedFileDataDTOFromJSON,
    UploadedFileDataDTOFromJSONTyped,
    UploadedFileDataDTOToJSON,
} from './UploadedFileDataDTO';

/**
 * 
 * @export
 * @interface UpdateUserPhotoRequestBody
 */
export interface UpdateUserPhotoRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserPhotoRequestBody
     */
    operationId: string;
    /**
     * 
     * @type {UploadedFileDataDTO}
     * @memberof UpdateUserPhotoRequestBody
     */
    uploadedFile: UploadedFileDataDTO;
}

/**
 * Check if a given object implements the UpdateUserPhotoRequestBody interface.
 */
export function instanceOfUpdateUserPhotoRequestBody(value: object): boolean {
    if (!('operationId' in value)) return false;
    if (!('uploadedFile' in value)) return false;
    return true;
}

export function UpdateUserPhotoRequestBodyFromJSON(json: any): UpdateUserPhotoRequestBody {
    return UpdateUserPhotoRequestBodyFromJSONTyped(json, false);
}

export function UpdateUserPhotoRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPhotoRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operationId'],
        'uploadedFile': UploadedFileDataDTOFromJSON(json['uploadedFile']),
    };
}

export function UpdateUserPhotoRequestBodyToJSON(value?: UpdateUserPhotoRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operationId': value['operationId'],
        'uploadedFile': UploadedFileDataDTOToJSON(value['uploadedFile']),
    };
}

