/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadedFileDataDTO
 */
export interface UploadedFileDataDTO {
    /**
     * 
     * @type {string}
     * @memberof UploadedFileDataDTO
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof UploadedFileDataDTO
     */
    bucketName: string;
    /**
     * 
     * @type {string}
     * @memberof UploadedFileDataDTO
     */
    objectName: string;
}

/**
 * Check if a given object implements the UploadedFileDataDTO interface.
 */
export function instanceOfUploadedFileDataDTO(value: object): boolean {
    if (!('url' in value)) return false;
    if (!('bucketName' in value)) return false;
    if (!('objectName' in value)) return false;
    return true;
}

export function UploadedFileDataDTOFromJSON(json: any): UploadedFileDataDTO {
    return UploadedFileDataDTOFromJSONTyped(json, false);
}

export function UploadedFileDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadedFileDataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'bucketName': json['bucketName'],
        'objectName': json['objectName'],
    };
}

export function UploadedFileDataDTOToJSON(value?: UploadedFileDataDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'bucketName': value['bucketName'],
        'objectName': value['objectName'],
    };
}

