/* tslint:disable */
/* eslint-disable */
/**
 * Users  API
 * Describes the API of Users Endpoint
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserWithSameEmailAlreadyExistsError
 */
export interface UserWithSameEmailAlreadyExistsError {
    /**
     * 
     * @type {string}
     * @memberof UserWithSameEmailAlreadyExistsError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithSameEmailAlreadyExistsError
     */
    message: string;
}

/**
 * Check if a given object implements the UserWithSameEmailAlreadyExistsError interface.
 */
export function instanceOfUserWithSameEmailAlreadyExistsError(value: object): boolean {
    if (!('code' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function UserWithSameEmailAlreadyExistsErrorFromJSON(json: any): UserWithSameEmailAlreadyExistsError {
    return UserWithSameEmailAlreadyExistsErrorFromJSONTyped(json, false);
}

export function UserWithSameEmailAlreadyExistsErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithSameEmailAlreadyExistsError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function UserWithSameEmailAlreadyExistsErrorToJSON(value?: UserWithSameEmailAlreadyExistsError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

