asyncapi: 3.0.0
info:
  title: Common Values
  version: 1.0.0
components:
  schemas:
    OperationId:
      x-service: common
      type: string
      format: uuid
    ListingId:
      x-service: common
      type: string
      format: uuid
    HostId:
      x-service: common
      type: string
      format: uuid
    UserId:
      x-service: common
      type: string
      format: uuid
    ErrorCode:
      x-service: common
      type: string
      enum:
        - NOT_FOUND
        - UNAUTHORIZED
        - FORBIDDEN
        - INVALID_PARAMETERS
        - INTERNAL_SERVER_ERROR
        - SERVICE_UNAVAILABLE
        - UNIMPLEMENTED
        - WRONG_FORMAT
    Error:
      x-service: common
      type: object
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string