openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /public/listings/promoted:
    get:
      tags:
        - queriesPublic
      operationId: getPromotedListings
      summary: Get promoted listings for home page
      responses:
        "200":
          description: List of listings
          content:
            application/json:
              schema:
                "$ref": "models.yaml#/components/schemas/GetPromotedListingsResponse"
