version: "2"

services:
  usersdb:
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
        POSTGRES_DB: usersdb