openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Users  API"
  description: Describes the API of Users Endpoint
paths:
  /api/public/verify-email:
    $ref: "commands/email-verification/paths.yaml#/paths/~1verify-email"
  /api/public/auth/sign-up:
    $ref: "commands/authentication/paths.yaml#/paths/~1sign-up"
  /api/public/auth/login:
      $ref: "commands/authentication/paths.yaml#/paths/~1login-by-email"

  /api/public/password/reset:
    $ref: "commands/reset-password/paths.yaml#/paths/~1reset"
  /api/public/password/set-new:
    $ref: "commands/reset-password/paths.yaml#/paths/~1set-new"

  /api/with-auth/users/current/photo/get-upload-url:
    $ref: "commands/update-user-photo/paths.yaml#/paths/~1get-upload-url"
  /api/with-auth/users/current/photo/update:
    $ref: "commands/update-user-photo/paths.yaml#/paths/~1update"

  /api/with-auth/users/current:
    $ref: "queries/current-user/paths.yaml#/paths/~1"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: [ ]
