spring:
  application:
    name: demobooking
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: username
    password: password
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:/schema.sql
app:
  security:
    jwt:
      publicKey: classpath:keys/public_key.pub
      privateKey: classpath:keys/private_key.key
      accessToken:
        expirationInMs: 100000
      refreshToken:
        expirationInMs: 100000