spring:
  application:
    name: users_microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: username
    password: password

  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:/schema.sql

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: letters-group-id
app:
  security:
    jwt:
      publicKey: classpath:keys/public_key.pub
      privateKey: classpath:keys/private_key.key
      accessToken:
        expirationInMs: 100000
      refreshToken:
        expirationInMs: 100000

  mail:
    username: username
    password: password
    host: 0.0.0.0
    port: 1025
    protocol: smtp

  verification_email:
    token_expiration_in_ms: 600000
    outgoing:
      fromName: username
      fromAddress: noreply@mail.com

    base_verification_link_url: http://localhost:8080/api/v1/users/verify