spring:
  application:
    name: demobooking
app:
  security:
    jwt:
      publicKey: classpath:keys/public_key.pub
      privateKey: classpath:keys/private_key.key
      accessToken:
        expirationInMs: 100000
      refreshToken:
        expirationInMs: 100000