/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddListingPhotoResponseBody
 */
export interface AddListingPhotoResponseBody {
    /**
     * 
     * @type {string}
     * @memberof AddListingPhotoResponseBody
     */
    operationId: string;
    /**
     * 
     * @type {string}
     * @memberof AddListingPhotoResponseBody
     */
    listingPhotoId: string;
}

/**
 * Check if a given object implements the AddListingPhotoResponseBody interface.
 */
export function instanceOfAddListingPhotoResponseBody(value: object): boolean {
    if (!('operationId' in value)) return false;
    if (!('listingPhotoId' in value)) return false;
    return true;
}

export function AddListingPhotoResponseBodyFromJSON(json: any): AddListingPhotoResponseBody {
    return AddListingPhotoResponseBodyFromJSONTyped(json, false);
}

export function AddListingPhotoResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddListingPhotoResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operationId'],
        'listingPhotoId': json['listingPhotoId'],
    };
}

export function AddListingPhotoResponseBodyToJSON(value?: AddListingPhotoResponseBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operationId': value['operationId'],
        'listingPhotoId': value['listingPhotoId'],
    };
}

