/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ModelError } from './ModelError';
import {
    instanceOfModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import type { ValidationError } from './ValidationError';
import {
    instanceOfValidationError,
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
} from './ValidationError';

/**
 * @type AddListing401Response
 * 
 * @export
 */
export type AddListing401Response = ModelError | ValidationError;

export function AddListing401ResponseFromJSON(json: any): AddListing401Response {
    return AddListing401ResponseFromJSONTyped(json, false);
}

export function AddListing401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddListing401Response {
    if (json == null) {
        return json;
    }
    return ModelErrorFromJSONTyped(json, true) || ValidationErrorFromJSONTyped(json, true);
}

export function AddListing401ResponseToJSON(value?: AddListing401Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfModelError(value)) {
        return ModelErrorToJSON(value as ModelError);
    }
    if (instanceOfValidationError(value)) {
        return ValidationErrorToJSON(value as ValidationError);
    }

    return {};
}

