/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddListingResponse
 */
export interface AddListingResponse {
    /**
     * 
     * @type {string}
     * @memberof AddListingResponse
     */
    listingId: string;
}

/**
 * Check if a given object implements the AddListingResponse interface.
 */
export function instanceOfAddListingResponse(value: object): boolean {
    if (!('listingId' in value)) return false;
    return true;
}

export function AddListingResponseFromJSON(json: any): AddListingResponse {
    return AddListingResponseFromJSONTyped(json, false);
}

export function AddListingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddListingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'],
    };
}

export function AddListingResponseToJSON(value?: AddListingResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'listingId': value['listingId'],
    };
}

