/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddListingRequestBody
 */
export interface AddListingRequestBody {
    /**
     * 
     * @type {string}
     * @memberof AddListingRequestBody
     */
    operationId: string;
    /**
     * 
     * @type {string}
     * @memberof AddListingRequestBody
     */
    title: string;
}

/**
 * Check if a given object implements the AddListingRequestBody interface.
 */
export function instanceOfAddListingRequestBody(value: object): boolean {
    if (!('operationId' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function AddListingRequestBodyFromJSON(json: any): AddListingRequestBody {
    return AddListingRequestBodyFromJSONTyped(json, false);
}

export function AddListingRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddListingRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operationId'],
        'title': json['title'],
    };
}

export function AddListingRequestBodyToJSON(value?: AddListingRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operationId': value['operationId'],
        'title': value['title'],
    };
}

