/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateUploadListingPhotoUrlRequestBody
 */
export interface GenerateUploadListingPhotoUrlRequestBody {
    /**
     * 
     * @type {string}
     * @memberof GenerateUploadListingPhotoUrlRequestBody
     */
    operationId?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateUploadListingPhotoUrlRequestBody
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateUploadListingPhotoUrlRequestBody
     */
    fileExtension?: string;
    /**
     * 
     * @type {number}
     * @memberof GenerateUploadListingPhotoUrlRequestBody
     */
    fileSize?: number;
}

/**
 * Check if a given object implements the GenerateUploadListingPhotoUrlRequestBody interface.
 */
export function instanceOfGenerateUploadListingPhotoUrlRequestBody(value: object): boolean {
    return true;
}

export function GenerateUploadListingPhotoUrlRequestBodyFromJSON(json: any): GenerateUploadListingPhotoUrlRequestBody {
    return GenerateUploadListingPhotoUrlRequestBodyFromJSONTyped(json, false);
}

export function GenerateUploadListingPhotoUrlRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateUploadListingPhotoUrlRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operationId'] == null ? undefined : json['operationId'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'fileExtension': json['fileExtension'] == null ? undefined : json['fileExtension'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
    };
}

export function GenerateUploadListingPhotoUrlRequestBodyToJSON(value?: GenerateUploadListingPhotoUrlRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operationId': value['operationId'],
        'fileName': value['fileName'],
        'fileExtension': value['fileExtension'],
        'fileSize': value['fileSize'],
    };
}

