/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingPrivateDetails } from './ListingPrivateDetails';
import {
    ListingPrivateDetailsFromJSON,
    ListingPrivateDetailsFromJSONTyped,
    ListingPrivateDetailsToJSON,
} from './ListingPrivateDetails';

/**
 * 
 * @export
 * @interface GetListingPrivateDetailsResponse
 */
export interface GetListingPrivateDetailsResponse {
    /**
     * 
     * @type {ListingPrivateDetails}
     * @memberof GetListingPrivateDetailsResponse
     */
    listing: ListingPrivateDetails;
}

/**
 * Check if a given object implements the GetListingPrivateDetailsResponse interface.
 */
export function instanceOfGetListingPrivateDetailsResponse(value: object): boolean {
    if (!('listing' in value)) return false;
    return true;
}

export function GetListingPrivateDetailsResponseFromJSON(json: any): GetListingPrivateDetailsResponse {
    return GetListingPrivateDetailsResponseFromJSONTyped(json, false);
}

export function GetListingPrivateDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListingPrivateDetailsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'listing': ListingPrivateDetailsFromJSON(json['listing']),
    };
}

export function GetListingPrivateDetailsResponseToJSON(value?: GetListingPrivateDetailsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'listing': ListingPrivateDetailsToJSON(value['listing']),
    };
}

