/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuestsCapacity
 */
export interface GuestsCapacity {
    /**
     * 
     * @type {number}
     * @memberof GuestsCapacity
     */
    adults: number;
    /**
     * 
     * @type {number}
     * @memberof GuestsCapacity
     */
    children: number;
    /**
     * 
     * @type {number}
     * @memberof GuestsCapacity
     */
    infants: number;
}

/**
 * Check if a given object implements the GuestsCapacity interface.
 */
export function instanceOfGuestsCapacity(value: object): boolean {
    if (!('adults' in value)) return false;
    if (!('children' in value)) return false;
    if (!('infants' in value)) return false;
    return true;
}

export function GuestsCapacityFromJSON(json: any): GuestsCapacity {
    return GuestsCapacityFromJSONTyped(json, false);
}

export function GuestsCapacityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestsCapacity {
    if (json == null) {
        return json;
    }
    return {
        
        'adults': json['adults'],
        'children': json['children'],
        'infants': json['infants'],
    };
}

export function GuestsCapacityToJSON(value?: GuestsCapacity | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'adults': value['adults'],
        'children': value['children'],
        'infants': value['infants'],
    };
}

