/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingPhotoPath
 */
export interface ListingPhotoPath {
    /**
     * 
     * @type {string}
     * @memberof ListingPhotoPath
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ListingPhotoPath
     */
    photoId: string;
}

/**
 * Check if a given object implements the ListingPhotoPath interface.
 */
export function instanceOfListingPhotoPath(value: object): boolean {
    if (!('url' in value)) return false;
    if (!('photoId' in value)) return false;
    return true;
}

export function ListingPhotoPathFromJSON(json: any): ListingPhotoPath {
    return ListingPhotoPathFromJSONTyped(json, false);
}

export function ListingPhotoPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingPhotoPath {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'photoId': json['photoId'],
    };
}

export function ListingPhotoPathToJSON(value?: ListingPhotoPath | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'photoId': value['photoId'],
    };
}

