/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
} from './Address';
import type { GuestsCapacity } from './GuestsCapacity';
import {
    GuestsCapacityFromJSON,
    GuestsCapacityFromJSONTyped,
    GuestsCapacityToJSON,
} from './GuestsCapacity';
import type { ListingPhotoPath } from './ListingPhotoPath';
import {
    ListingPhotoPathFromJSON,
    ListingPhotoPathFromJSONTyped,
    ListingPhotoPathToJSON,
} from './ListingPhotoPath';
import type { ListingStatus } from './ListingStatus';
import {
    ListingStatusFromJSON,
    ListingStatusFromJSONTyped,
    ListingStatusToJSON,
} from './ListingStatus';
import type { PropertyType } from './PropertyType';
import {
    PropertyTypeFromJSON,
    PropertyTypeFromJSONTyped,
    PropertyTypeToJSON,
} from './PropertyType';
import type { RoomType } from './RoomType';
import {
    RoomTypeFromJSON,
    RoomTypeFromJSONTyped,
    RoomTypeToJSON,
} from './RoomType';

/**
 * 
 * @export
 * @interface ListingPrivateDetails
 */
export interface ListingPrivateDetails {
    /**
     * 
     * @type {string}
     * @memberof ListingPrivateDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListingPrivateDetails
     */
    title: string;
    /**
     * 
     * @type {ListingStatus}
     * @memberof ListingPrivateDetails
     */
    status: ListingStatus;
    /**
     * 
     * @type {string}
     * @memberof ListingPrivateDetails
     */
    description?: string;
    /**
     * 
     * @type {GuestsCapacity}
     * @memberof ListingPrivateDetails
     */
    guestCapacity: GuestsCapacity;
    /**
     * 
     * @type {PropertyType}
     * @memberof ListingPrivateDetails
     */
    propertyType?: PropertyType;
    /**
     * 
     * @type {RoomType}
     * @memberof ListingPrivateDetails
     */
    roomType?: RoomType;
    /**
     * 
     * @type {Address}
     * @memberof ListingPrivateDetails
     */
    address?: Address;
    /**
     * 
     * @type {object}
     * @memberof ListingPrivateDetails
     */
    location?: object;
    /**
     * 
     * @type {Array<ListingPhotoPath>}
     * @memberof ListingPrivateDetails
     */
    photos?: Array<ListingPhotoPath>;
}

/**
 * Check if a given object implements the ListingPrivateDetails interface.
 */
export function instanceOfListingPrivateDetails(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('title' in value)) return false;
    if (!('status' in value)) return false;
    if (!('guestCapacity' in value)) return false;
    return true;
}

export function ListingPrivateDetailsFromJSON(json: any): ListingPrivateDetails {
    return ListingPrivateDetailsFromJSONTyped(json, false);
}

export function ListingPrivateDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingPrivateDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'status': ListingStatusFromJSON(json['status']),
        'description': json['description'] == null ? undefined : json['description'],
        'guestCapacity': GuestsCapacityFromJSON(json['guestCapacity']),
        'propertyType': json['propertyType'] == null ? undefined : PropertyTypeFromJSON(json['propertyType']),
        'roomType': json['roomType'] == null ? undefined : RoomTypeFromJSON(json['roomType']),
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'location': json['location'] == null ? undefined : json['location'],
        'photos': json['photos'] == null ? undefined : ((json['photos'] as Array<any>).map(ListingPhotoPathFromJSON)),
    };
}

export function ListingPrivateDetailsToJSON(value?: ListingPrivateDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'status': ListingStatusToJSON(value['status']),
        'description': value['description'],
        'guestCapacity': GuestsCapacityToJSON(value['guestCapacity']),
        'propertyType': PropertyTypeToJSON(value['propertyType']),
        'roomType': RoomTypeToJSON(value['roomType']),
        'address': AddressToJSON(value['address']),
        'location': value['location'],
        'photos': value['photos'] == null ? undefined : ((value['photos'] as Array<any>).map(ListingPhotoPathToJSON)),
    };
}

