/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ListingStatus = {
    Published: 'PUBLISHED',
    Draft: 'DRAFT',
    ReadyForPublishing: 'READY_FOR_PUBLISHING'
} as const;
export type ListingStatus = typeof ListingStatus[keyof typeof ListingStatus];


export function instanceOfListingStatus(value: any): boolean {
    return Object.values(ListingStatus).includes(value);
}

export function ListingStatusFromJSON(json: any): ListingStatus {
    return ListingStatusFromJSONTyped(json, false);
}

export function ListingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingStatus {
    return json as ListingStatus;
}

export function ListingStatusToJSON(value?: ListingStatus | null): any {
    return value as any;
}

