/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RoomType = {
    EntirePlace: 'ENTIRE_PLACE',
    PrivateRoom: 'PRIVATE_ROOM',
    SharedRoom: 'SHARED_ROOM'
} as const;
export type RoomType = typeof RoomType[keyof typeof RoomType];


export function instanceOfRoomType(value: any): boolean {
    return Object.values(RoomType).includes(value);
}

export function RoomTypeFromJSON(json: any): RoomType {
    return RoomTypeFromJSONTyped(json, false);
}

export function RoomTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomType {
    return json as RoomType;
}

export function RoomTypeToJSON(value?: RoomType | null): any {
    return value as any;
}

