/* tslint:disable */
/* eslint-disable */
/**
 * Listings API
 * Describes the API of Listings service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateListingDetailsFields } from './UpdateListingDetailsFields';
import {
    UpdateListingDetailsFieldsFromJSON,
    UpdateListingDetailsFieldsFromJSONTyped,
    UpdateListingDetailsFieldsToJSON,
} from './UpdateListingDetailsFields';

/**
 * 
 * @export
 * @interface UpdateListingDetailsRequestBody
 */
export interface UpdateListingDetailsRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateListingDetailsRequestBody
     */
    operationId: string;
    /**
     * 
     * @type {UpdateListingDetailsFields}
     * @memberof UpdateListingDetailsRequestBody
     */
    fields: UpdateListingDetailsFields;
}

/**
 * Check if a given object implements the UpdateListingDetailsRequestBody interface.
 */
export function instanceOfUpdateListingDetailsRequestBody(value: object): boolean {
    if (!('operationId' in value)) return false;
    if (!('fields' in value)) return false;
    return true;
}

export function UpdateListingDetailsRequestBodyFromJSON(json: any): UpdateListingDetailsRequestBody {
    return UpdateListingDetailsRequestBodyFromJSONTyped(json, false);
}

export function UpdateListingDetailsRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateListingDetailsRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'operationId': json['operationId'],
        'fields': UpdateListingDetailsFieldsFromJSON(json['fields']),
    };
}

export function UpdateListingDetailsRequestBodyToJSON(value?: UpdateListingDetailsRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operationId': value['operationId'],
        'fields': UpdateListingDetailsFieldsToJSON(value['fields']),
    };
}

