openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  \:
components:
  schemas:
    ListingPrivateDetails:
      type: object
      required:
        - id
        - title
        - status
        - guestCapacity
      properties:
        id:
          $ref: "../../common/models/ListingId.yaml"
        title:
          type: string
        status:
          $ref: "../../common/models/ListingStatus.yaml"
        description:
          type: string
        guestCapacity:
          $ref: "../../common/models/GuestsCapacity.yaml"
        propertyType:
          $ref: "../../common/models/PropertyType.yaml"
        roomType:
          $ref: "../../common/models/RoomType.yaml"
        address:
          $ref: "../../common/models/Address.yaml"
        location:
          $ref: "../../common/models/Location.yaml"
        photos:
          type: array
          items:
            $ref: "../../common/models/ListingPhotoPath.yaml"

    GetPhotoUploadUrlForListingResponse:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri

    GetListingPrivateDetailsResponse:
      type: object
      required:
        - listing
      properties:
        listing:
          $ref: "#/components/schemas/ListingPrivateDetails"