openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  \:
components:
  schemas:
    ListingPrivateDetailsDTO:
      type: object
      required:
        - id
        - title
        - status
      properties:
        id:
          $ref: "../../common/models/ListingIdDTO.yaml"
        title:
          type: string
        status:
          $ref: "../../common/models/ListingStatusDTO.yaml"
        description:
          type: string
        guestCapacity:
          $ref: "../../common/models/GuestsCapacityDTO.yaml"
        propertyType:
          $ref: "../../common/models/PropertyTypeDTO.yaml"
        roomType:
          $ref: "../../common/models/RoomTypeDTO.yaml"
        address:
          $ref: "../../common/models/AddressDTO.yaml"
        location:
          $ref: "../../common/models/LocationDTO.yaml"
        photos:
          type: array
          items:
            $ref: "../../common/models/ListingPhotoPathDTO.yaml"

    GetPhotoUploadUrlForListingResponse:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri

    GetListingPrivateDetailsResponse:
      type: object
      required:
        - listing
      properties:
        listing:
          $ref: "#/components/schemas/ListingPrivateDetailsDTO"