openapi: 3.0.3
info:
  title: Domain events API
  description: Domain events API
  version: 1.0.0
paths:
  /do_nothing:
    get:
      summary: Does nothing
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    UsersDomainEvent:
      type: object
      required:
        - domain
        - eventId
        - occurredAt
        - eventType
        - payload
      properties:
        domain:
          type: string
          enum:
            - USERS
          default: USERS
        eventId:
          type: string
        occurredAt:
          type: integer
          format: int64
        payload:
          $ref: '#/components/schemas/UsersDomainEventPayload'

    UsersDomainEventPayload:
      discriminator:
        propertyName: type
      oneOf:
        - $ref: '#/components/schemas/UserSignedUp'
        #              Email verification
        - $ref: '#/components/schemas/UserVerifiedEmail'
        - $ref: '#/components/schemas/VerificationEmailSent'
        - $ref: '#/components/schemas/FailedToSendVerificationEmail'
        - $ref: '#/components/schemas/CompleteEmailVerification'
        - $ref: '#/components/schemas/SendVerificationEmail'

        #              Password reset
        - $ref: '#/components/schemas/SentEmailForPasswordReset'
        - $ref: '#/components/schemas/CompletePasswordReset'
        - $ref: '#/components/schemas/UserDidResetPassword'
        #              Photo
        - $ref: '#/components/schemas/GeneratedUserPhotoUploadUrl'
        - $ref: '#/components/schemas/UpdatedUserPhoto'
        - $ref: '#/components/schemas/FailedUpdateUserPhoto'
        - $ref: '#/components/schemas/FailedGenerateUserPhotoUploadUrl'

    FullName:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        lastName:
          type: string

    SendVerificationEmail:
      type: object
      required:
        - userId
        - email
        - fullName
        - attempt
      properties:
        userId:
          type: string
        email:
          type: string
        fullName:
          $ref: '#/components/schemas/FullName'
        attempt:
          type: integer

    VerificationEmailSent:
      type: object
      required:
        - userId
        - email
      properties:
        userId:
          type: string
        email:
          type: string

    UserVerifiedEmail:
      type: object
      required:
        - userId
        - email
      properties:
        userId:
          type: string
        email:
          type: string

    FailedToSendVerificationEmail:
      type: object
      required:
        - userId
        - email
        - attempts
      properties:
        userId:
          type: string
        email:
          type: string
        attempts:
          type: integer

    CompleteEmailVerification:
      type: object
      required:
        - emailVerificationToken
      properties:
        emailVerificationToken:
          type: string

    UploadedFileData:
      type: object
      required:
        - bucketName
        - objectName
      properties:
        bucketName:
          type: string
        objectName:
          type: string

    UserPhotoPath:
      type: object
      required:
        - bucketName
        - objectName
      properties:
        bucketName:
          type: string
        objectName:
          type: string

    UpdatedUserPhoto:
      type: object
      required:
        - userId
        - newPhotoPath
      properties:
        userId:
          type: string
        newPhotoPath:
          $ref: '#/components/schemas/UserPhotoPath'
        prevPhotoPath:
          $ref: '#/components/schemas/UserPhotoPath'

    GenerateUserPhotoUploadUrl:
      type: object
      required:
        - userId
        - fileExtension
        - fileSize
        - operationId
        - requestedAt
      properties:
        userId:
          type: string
        fileExtension:
          type: string
        fileSize:
          type: integer
        operationId:
          type: string
        requestedAt:
          type: integer
          format: int64

    GeneratedUserPhotoUploadUrl:
      type: object
      required:
        - userId
        - formData
      properties:
        userId:
          type: string
        formData:
          $ref: '#/components/schemas/UploadedFileFormData'

    FailedUpdateUserPhoto:
      type: object
      required:
        - operationId
        - userId
        - uploadedFileData
      properties:
        operationId:
          type: string
        userId:
          type: string
        uploadedFileData:
          $ref: '#/components/schemas/UploadedFileData'

    FailedGenerateUserPhotoUploadUrl:
      type: object
      required:
        - userId
        - fileExtension
        - fileSize
        - operationId
      properties:
        userId:
          type: string
        fileExtension:
          type: string
        fileSize:
          type: integer
        operationId:
          type: string

    UserDidResetPassword:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string

    UserSignedUp:
      type: object
      required:
        - createdAt
        - userId
        - fullName
        - email
        - emailVerificationStatus
      properties:
        createdAt:
          type: integer
          format: int64
        userId:
          type: string
        fullName:
          $ref: '#/components/schemas/FullName'
        email:
          type: string
        emailVerificationStatus:
          type: string

    SentEmailForPasswordReset:
      type: object
      required:
        - userId
        - email
      properties:
        userId:
          type: string
        email:
          type: string

    CompletePasswordReset:
      type: object
      required:
        - operationId
        - newPassword
        - passwordResetToken
      properties:
        operationId:
          type: string
        newPassword:
          type: string
        passwordResetToken:
          type: string

    UploadedFileFormData:
        type: object
        required:
            - url
            - bucketName
            - objectName
            - formData
        properties:
            url:
              type: string
              format: uri
            bucketName:
              type: string
            objectName:
              type: string
            formData:
              type: object
              additionalProperties:
                type: string